### ISSUE TITLE
Demo not working?

### ISSUE THREAD

**Issue by JekSun97** [nndda/Theatre#21]
I press Enter and Space, but the dialog doesn't start, I just have a blank panel

All action keys are set to default, I checked

I ran demo_scene.tscn

**Comment by nndda** [comment]
Ah, sorry for the confusion! the `demo_scene.tscn` was actually the base scene for the demos. The playable demo scenes are:
- `res://theatre_demo/1_intro.tscn`
- `res://theatre_demo/preview/preview.tscn`

Although, you may want to comment these lines on `preview.tscn`'s script, since it ends the demo immediately after the first dialogue line finished.

https://github.com/nndda/Theatre/blob/cf90e355e7073f34687536cf640e35fe47b52182/theatre_demo/preview/preview.gd#L33-L34
